export const CHANGE_CALC_TYPE = "CHANGE_CALC_TYPE";
// export const CHANGE_ACTIVE_STEP_INDEX = "CHANGE_ACTIVE_STEP_INDEX";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const CHANGE_CURRENCY_LABEL = "CHANGE_CURRENCY_LABEL";
export const CHANGE_LOAN_AMOUNT = "CHANGE_LOAN_AMOUNT";
export const CHANGE_INTEREST_RATE = "CHANGE_INTEREST_RATE";
export const CHANGE_NUMBER_OF_PERIODS = "CHANGE_NUMBER_OF_PERIODS";
export const UPDATE_CHART_DATA = "UPDATE_CHART_DATA";
